### ISSUE TITLE
Fix ?

### ISSUE THREAD

**Issue by Galixte** [dmzx/youtubegallery#27]
Hi @vinny  @dmzx,

could you take a look about that ? https://www.phpbb.com/community/viewtopic.php?p=14190726#p14190726

**Comment by vinny** [comment]
https://www.phpbb.com/community/viewtopic.php?p=14226386#p14226386

**Comment by Galixte** [comment]
Thanks, @bb3mobi what do you think ?

**Comment by vinny** [comment]
@bb3mobi Are you there?
