### ISSUE TITLE
Title of categorie by default

### ISSUE THREAD

**Issue by Galixte** [dmzx/youtubegallery#28]
Hi @vinny  @dmzx,

could you make the title of the default category multilanguage ? (by adding a new language key ?)

https://github.com/dmzx/youtubegallery/blob/master/migrations/youtubegallery_sample.php#L37

Because this title doesn’t make sense for people which don’t speak english.

**Comment by vinny** [comment]
Probably we should change it. 
https://github.com/dmzx/youtubegallery/blob/master/language/en/common.php#L140

**Comment by Galixte** [comment]
Yes, but It’s not a multilangual solution.

**Comment by Galixte** [comment]
Ok, since your fix: https://github.com/dmzx/youtubegallery/issues/30#issuecomment-147110296, i discovered the “Video Categories” and it’s possible to delete the default category. So, it’s ok for me, thanks.
