### ISSUE TITLE
Why a title module make no sense ?

### ISSUE THREAD

**Issue by Galixte** [dmzx/youtubegallery#29]
Hi @vinny  @dmzx,

why this title: https://github.com/dmzx/youtubegallery/blob/master/acp/acp_youtubegallery_info.php#L19.

It should be ```ACP_VIDEO```, no ?

**Comment by vinny** [comment]
Fixed: https://github.com/dmzx/youtubegallery/commit/38e40862f44da736773bf1671c29ed9159e2385c
