### ISSUE TITLE
Vidéo categories ?

### ISSUE THREAD

**Issue by Galixte** [dmzx/youtubegallery#30]
Hi @vinny  @dmzx,

in ACP, in EXTENSIONS tab, i see:
- VIDEO GALLERY
  - Video Settings
  - Video Titles

I don’t see Video Categories.

**Comment by vinny** [comment]
Fixed: https://github.com/dmzx/youtubegallery/commit/8e0f09539639e9141e8fba411351cf6587c9fdb3

**Comment by Galixte** [comment]
Thanks Vinny!
