### ISSUE TITLE
Videos per page

### ISSUE THREAD

**Issue by vinny** [dmzx/youtubegallery#43]
https://www.phpbb.com/customise/db/extension/youtube_videos_gallery/support/topic/176771?p=559896#p559896

Add a new config option

**Comment by dmzx** [comment]
Yes will add this option.

**Comment by vinny** [comment]
👍

**Comment by dmzx** [comment]
Need to update language file for this.
Delete the others languages?

**Comment by vinny** [comment]
Need a new migration too.

Keep the language files and add the changes to them, maybe the translators can update soon. if not remove them.

**Comment by dmzx** [comment]
Did delete them and will ask translators to make them ;P

https://github.com/dmzx/youtubegallery/commit/15f500c270d2151885238b3e43ed11322478ad47

**Comment by dmzx** [comment]
When tested can be closed.

**Comment by vinny** [comment]
All Ok!
