### ISSUE TITLE
mChat intergration

### ISSUE THREAD

**Issue by dmzx** [dmzx/youtubegallery#44]
New feature to integrate with mChat when posting new video.
New post will be added directly into mChat.

Let me know :P

**Comment by dmzx** [comment]
Want to use flash for it.
Do you want to be able to set the with/width for flash?

**Comment by Galixte** [comment]
Why FLASH it’s useless, HTML5 instead, no ?

**Comment by vinny** [comment]
@dmzx Where you implemented this, could you show some screenshot?

@Galixte Probably because we have Flash BBcode. Anyway, youtube displays the video as html5

**Comment by dmzx** [comment]
@vinny this is result of new uploaded video

![youtoubemchat](https://cloud.githubusercontent.com/assets/6445099/26023720/080eeb88-37c3-11e7-8cf3-2345bd759e90.PNG)

**Comment by dmzx** [comment]
![youtoubemchatacp](https://cloud.githubusercontent.com/assets/6445099/26023732/44d764f0-37c3-11e7-9144-c58582e4f92e.PNG)

ACP settings

**Comment by vinny** [comment]
@mchat_posting: Maybe switch to something simpler like:
> User_x added a new video: [My awesome title](https://github.com/) on 01 jan 2017

If we use only this, no width/height settings are required.

If mChat is not installed, will these options be displayed?

**Comment by dmzx** [comment]
A Yes maybe better to like that.

> If mChat is not installed, will these options be displayed?

Yes correct if not installed settings will not be displayed.

**Comment by vinny** [comment]
👍

**Comment by vinny** [comment]
any news?

**Comment by dmzx** [comment]
did push it finally here..
